# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-19 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
